dbgapi/msvc: Fix build error with missing typename
MSVC currently shows this build error:

 D:\therock\src\rocm-systems\projects\rocdbgapi\src\architecture.cpp(7940): error C7510: 'value_type': use of dependent type name must be prefixed with 'typename'
 ... followed by cascading build errors...

Fix it by adding "typename".

Change-Id: Idb1743c43e70c63416a76acc9590765113ffa0eb
commit-id:f0dce83e