dbgapi/msvc: dbgapi_assert_not_reached
MSVC does not have __builtin_trap, resulting in:

 D:\therock\src\rocm-systems\projects\rocdbgapi\src\queue.h(187): error C3861: '__builtin_trap': identifier not found

... and many more of the same.

Reimplement dbgapi_assert_not_reached using __debugbreak + abort.  Add
the abort to match better the semantics of __builtin_trap, which is
noreturn.  I.e., to avoid someone catching the __debugbreak in a
debugger an then continuing after the trap.

Change-Id: Ic3e0fa5dfd686150a7b9f61564371e521e28d095
commit-id:26be3cb4